name: SANDRA KONG
favicon: null
layout_spectrum: 0.82684
typography_spectrum: 0.672884242143482
title: 'SANDRA KONG | PORTFOLIO'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#794e2c'
    - '#acacac'
    - '#96806f'
    - '#8c1e1a'
  brandStrength: 0.6875
  lightness: 0.16282645030878484
  saturation: 0.26619760249741375
  rhythmicContrast: 0.25
purpose: []
